language: node_js

node_js:
  # latest stable node version
  - "stable" 

# whitelist
branches:
 only:
   - master
  
before_script:
  - cd client
  - npm install
  - cd server
  - npm install

script:
  # start the server and test back-end
  - node server.js &
  - npm test
  # perform front-end tests 
  - cd ../client
  - npm test