language: node_js

node_js:
  # latest node version
  - "node" 

# whitelist
branches:
 only:
   - master
  
before_script:
  - cd server
  - npm install

script:
  - cd server
  - node server.js &
  - npm test