swagger: '2.0'

info:
  version: "1.0.0"
  title: TA-Recommender
  description: The recommendation component of the overall TA coordinator system
schemes:
  - http
  - https
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
paths:
  /recommend/:
   post:
      description: |
        returns a list of recommended applicants for a given course
      security:
       - basicAuth: []
      parameters:
        - name: session
          in: query
          description: session token to identify the user and ensure permissable access
          required: true
          type: string
        - name: limit
          in: query
          description: limits the number of recommendations
          required: false
          type: integer
        - name: course
          in: body
          description: course to recommend for
          required: true
          schema:
            $ref: '#/definitions/Applicant'
      responses:
        200:
          description: list of suggested applications
          schema:
            type: array
            items:
              $ref: '#/definitions/Applicant'
        default: 
          description: indicates operation success, returns error if applicable
          schema:
            $ref: '#/definitions/Success'
definitions:
  Applicant:
    type: object
    properties:
      a_id:  # would be student id
        type: integer
        format: int32
      password:  # to be hashed
        type: string
        format: password
      family_name:
        type: string
      given_name:
        type: string
      program:  # undergrad, masters, phd
        type: string
      year:
        type: integer
      ta_courses:  # past courses ta'd
        type: array
        items:
          $ref: '#/definitions/Course'
      courses:  # courses taken
        type: array
        items:
          type: integer
      phone:
        type: integer
        format: int32
      email:
        type: string
      work_status:
        type: string
      work_status_explanation:
        type: string
      department:
        type: string
      department_explanation:
        type: string
      experience:
        type: string
      appy_date:
        type: string
        format: dateTime
      applied_courses:
        type: array
        items:
          $ref: '#/definitions/Course'
      offers:
        type: array
        items:
          $ref: '#/definitions/Offer'
      active_offers:  # offers taken by applicant
        type: array
        items:
          $ref: '#/definitions/Offer'
  Course:
    type: object
    properties:
      c_id:  # course id 
        type: integer
        format: int32
      head_instructor:  # lead instructor for course, has managmennt permission
        $ref: '#/definitions/Instructor'
      additional_instructors:
        type: array
        items:
          $ref: '#/definitions/Instructor'
      name:
        type: string
      semester:
        type: string
      start_date:
        type: string
        format: date
      expected_enrollment:  # expected size of class
        type: integer
      preference:  # instructor message to coordinator
        type: string
      desired_applicants:  # applicants instructor requests
        type: array
        items:
          $ref: '#/definitions/Applicant'
      avoid_applicants:  # applicants instructor does not want
        type: array
        items:
          $ref: '#/definitions/Applicant'
      assigned_applicants:
        type: array
        items:
          $ref: '#/definitions/Applicant'
      flagged_applicants:
        type: array
        items:
          $ref: '#/definitions/Applicant'
      tas:
        type: array
        items:
          $ref: '#/definitions/Applicant'
  Offer:
    type: object
    properties:
      o_id:
        type: integer
        format: int32
      course:
        $ref: '#/definitions/Course'
      applicant:
        $ref: '#/definitions/Applicant'
      hours:
        type: integer
      approved:
        type: boolean
      accepted:
        type: boolean
  Instructor:
    type: object
    properties:
      i_id:  # instructor id, employee number
        type: integer
        format: int32
      family_name: 
        type: string
      given_name:
        type: string
      email:
        type: string
  Success:
    type: object
    properties:
      success:
        type: boolean
      error_code:
        type: integer
        format: int32
      error_mst:
        type: string